### ISSUE TITLE
annlite failed to build on M1 Mac

### ISSUE THREAD

**Issue by ZiniuYu** [jina-ai/annlite#116]
Python version: 3.9
MacOS version: 12.2.1
CMD used: pip install https://github.com/jina-ai/annlite/archive/refs/heads/main.zip (or pip install "docarray[full]")
Error log:
> Building wheels for collected packages: annlite
  Building wheel for annlite (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/envs/jina/bin/python /opt/anaconda3/envs/jina/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn/T/tmps65jnhoh
       cwd: /private/var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn/T/pip-req-build-zbgplt5p
  Complete output (48 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.1-arm64-cpython-39
  creating build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/enums.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/index.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/profile.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/container.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/utils.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/helper.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/filter.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  copying annlite/math.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite
  creating build/lib.macosx-11.1-arm64-cpython-39/annlite/core
  copying annlite/core/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core
  creating build/lib.macosx-11.1-arm64-cpython-39/annlite/storage
  copying annlite/storage/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/storage
  copying annlite/storage/kv.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/storage
  copying annlite/storage/table.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/storage
  copying annlite/storage/base.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/storage
  creating build/lib.macosx-11.1-arm64-cpython-39/annlite/core/codec
  copying annlite/core/codec/vq.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/codec
  copying annlite/core/codec/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/codec
  copying annlite/core/codec/pq.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/codec
  copying annlite/core/codec/base.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/codec
  creating build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index
  copying annlite/core/index/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index
  copying annlite/core/index/pq_index.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index
  copying annlite/core/index/flat_index.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index
  copying annlite/core/index/base.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index
  creating build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index/hnsw
  copying annlite/core/index/hnsw/index.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index/hnsw
  copying annlite/core/index/hnsw/__init__.py -> build/lib.macosx-11.1-arm64-cpython-39/annlite/core/index/hnsw
  running build_ext
  creating var
  creating var/folders
  creating var/folders/8m
  creating var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn
  creating var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn/T
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/anaconda3/envs/jina/include -arch arm64 -I/opt/anaconda3/envs/jina/include -fPIC -O2 -isystem /opt/anaconda3/envs/jina/include -arch arm64 -I/opt/anaconda3/envs/jina/include/python3.9 -c /var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn/T/tmplkc2w81j.cpp -o var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn/T/tmplkc2w81j.o -std=c++14
  building 'annlite.hnsw_bind' extension
  creating build/temp.macosx-11.1-arm64-cpython-39
  creating build/temp.macosx-11.1-arm64-cpython-39/bindings
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /opt/anaconda3/envs/jina/include -arch arm64 -I/opt/anaconda3/envs/jina/include -fPIC -O2 -isystem /opt/anaconda3/envs/jina/include -arch arm64 -I/private/var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn/T/pip-build-env-ibiuvri9/overlay/lib/python3.9/site-packages/pybind11/include -I/private/var/folders/8m/b8y6xg410sz19rwf9v_6fqch0000gn/T/pip-build-env-ibiuvri9/overlay/lib/python3.9/site-packages/numpy/core/include -I./include/hnswlib -I/opt/anaconda3/envs/jina/include/python3.9 -c ./bindings/hnsw_bindings.cpp -o build/temp.macosx-11.1-arm64-cpython-39/./bindings/hnsw_bindings.o -O3 -march=native -stdlib=libc++ -mmacosx-version-min=10.7 -DVERSION_INFO=\"0.3.2\" -std=c++14
  clang: error: the clang compiler does not support '-march=native'
  error: command '/usr/bin/clang' failed with exit code 1
+++
  ERROR: Failed building wheel for annlite
Failed to build annlite
ERROR: Could not build wheels for annlite which use PEP 517 and cannot be installed directly

**Comment by numb3r3** [comment]
It is recommended to use Rosetta on M1, referring to https://docs.jina.ai/get-started/install/troubleshooting/#on-mac-m1

**Comment by ZiniuYu** [comment]
Ok, Thanks. For everyone encountered this problem, make sure you use Rosetta to build codes. And for Anaconda users, please use Rosetta to install python. (FYI https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/)

**Comment by jpzhangvincent** [comment]
Is it possible to build in minforge conda so we can use the GPU enabled tensorflow/pytorch on M1 Mac ?
