### ISSUE TITLE
Add comments for py 

### ISSUE THREAD

**Issue by gusye1234** [jina-ai/annlite#119]
Hi, 
I'm reading the main body of `annlite`, and I found some core functions lack comments, which may cause some confusion(at least to me).
Maybe I can add some comments while I'm reading, and open a PR for that?

**Comment by numb3r3** [comment]
absolutely this is a good idea.

**Comment by gusye1234** [comment]
Cool! 
So maybe there are some recommended comment styles in Jina for Python?

**Comment by numb3r3** [comment]
Please follow the docstr style used in docarray, for example https://github.com/jina-ai/docarray/blob/main/docarray/document/mixins/audio.py

**Comment by gusye1234** [comment]
Got it.
But I still have one small question. So I looked down `docarray` repo, and didn't find a proper way to "docstring" multiple returns. I found one in [here](https://github.com/jina-ai/docarray/blob/24301254d95fd755fb6e821df6bc2c6b977b138b/docarray/math/ndarray.py#L90-L97):
```python
def get_array_type(
    array: 'ArrayType', raise_error_if_not_array: bool = True
) -> Tuple[str, bool]:
    """Get the type of ndarray without importing the framework

    :param array: any array, scipy, numpy, tf, torch, etc.
    :return: a tuple where the first element represents the framework, the second represents if it is sparse array
    """
```
But this way seems a little bit not intuitive to me. Does the below way look better?
```python
def get_array_type(
    array: 'ArrayType', raise_error_if_not_array: bool = True
) -> Tuple[str, bool]:
    """Get the type of ndarray without importing the framework

    :param array: any array, scipy, numpy, tf, torch, etc.

    :return: the framework, 
    :return: if it is sparse array
    """
```
Since no matter `google` or `numpy` docstring style will separate multiple returns into multiple lines.

**Comment by numb3r3** [comment]
@gusye1234 Actually, for me personality, I prefer the first style, which is more human-readable.
