### ISSUE TITLE
Filtering using $in keyword crashes the executors and the database

### ISSUE THREAD

**Issue by mirzakhalov** [jina-ai/annlite#124]
I have a simple flow that looks like this:

```python
f = (
    Flow(port_expose=8082, protocol='http', monitoring=True, port_monitoring=9090)
    .add(name='encoder', uses='jinahub+docker://CLIPEncoder')
    .add(name='processor',
         uses='jinahub+docker://PQLiteIndexer/latest',
         uses_with={
            'dim': 512,
            'columns': columns
         },
    )
)
```

Indexing works fine and I can verify it using `/status` endpoint where it shows the number of indexed documents. When I hit the `/search` endpoint, I can search and retrieve results correctly. 

I also verified that filtering works by testing it with `$eq`. However, when I test it with `$in`, things go south. Not only does it not return any results, but it also seems to crash my entire database where I can't make calls to endpoints like `/status`and `/search`. Does anyone have any idea as to what is happening? Here is how I am structuring my filter query:

```python
# this query searches the files with a tag 'owners' of type array which includes the given string
search_results = c.post(on="/search",
                 parameters={
                     "query": QUERIES[0],
                     "traversal_paths": '@r,c',
                     "limit": 3,
                     "filter":{"owners": {"$in": ["EGGWLJSUHT6GLWU2KIB0"]}}
                 })
```

**Comment by JoanFM** [comment]
Hey @mirzakhalov,

Can you provide some more details, perhaps even some small dataset and show what the exact error u are getting?

**Comment by JoanFM** [comment]
Hey @mirzakhalov ,

May you try using `ANNLiteIndexer` instead of `PQLiteIndexer`? `pqlite` was renamed `annlite` and consequently the `executor` in the hub was changed and so the new features will be available in there
