### ISSUE TITLE
feature request: get doucment from annlite by document id.

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/annlite#128]
Hi,

it would be nice to have option to retrieve document by its id from lmdb.
Now it is possible via

 `_index.doc_store(0).get(['document_id'])}` which is not cumbersome given number of different cells.

thank you

**Comment by numb3r3** [comment]
Thanks for your interest. You can simply use this API `get_doc_by_id(doc_id)` to get doc by its id.
