### ISSUE TITLE
Workspace size double during first use (query time init)

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/annlite#141]
Hello,

I have large dataset. My workspace is 27GB after indexing (I have sent. embeddings, token embeddings and metadata).
But after first inference init workspace grows to 53 GB which is totally strange.

I have 
annlite==0.3.5
jina==3.6.9

Any clues why this is happening?

Thanks

**Comment by jemmyshin** [comment]
There is something wrong with loading the indexer from the disk which will double the workspace, we are trying to fix this, thanks for pointing it out.

**Comment by tommykoctur** [comment]
Thank you, 

do you have any update on this ?

Thanks

**Comment by numb3r3** [comment]
@tommykoctur We are working on it. The patch will be released by Tomorrow.

**Comment by jemmyshin** [comment]
@tommykoctur Hi, we have released a new version to fix this issue. Please try it again.

**Comment by tommykoctur** [comment]
HI @numb3r3 @jemmyshin thank you for your effort.
I have installed:

```pip install git+https://github.com/jina-ai/annlite.git@b602acce8f7f2ac085f9cbccae6fadeee1ebcb85```

I can confirm that it works, and workspace is not double, it is slight increase and some new files are there.
Before:
```
27G     workspace/cell_0
27G     workspace
```
Now (with the same dataset):
```
1,3G    workspace/snapshot-4578fd099e1f6581d36464d45b50131e/2022-08-23#22:31:25-SNAPSHOT
1,3G    workspace/snapshot-4578fd099e1f6581d36464d45b50131e
4,0K    workspace/parameters-4578fd099e1f6581d36464d45b50131e
27G     workspace/cell_0
28G     workspace
```

Is this correct behaviour ?

**Comment by tommykoctur** [comment]
I have noticed that first inference load is very slow tens of minutes for such a big dataset, but after those snapshots are calculated another start is very fast. 
I like it.

**Comment by jemmyshin** [comment]
Yes, we will create some snapshots and it will load the indexer from these files so it will be faster.

**Comment by tommykoctur** [comment]
Great thank you. Very good job. !
