### ISSUE TITLE
Can't be installed in Mac M1 chip

### ISSUE THREAD

**Issue by hsalehgh** [jina-ai/annlite#145]
I am trying to install `annlite` in my macbook with M1 chip using `pip install annlite` but I receive the following error:
```
clang: error: the clang compiler does not support '-march=native'
      error: command '/usr/bin/clang' failed with exit code 1
```
Is there any suggestion to fix it?

**Comment by ZiniuYu** [comment]
Hi @hsalehgh , please try again using Rosetta https://github.com/jina-ai/annlite/issues/116

**Comment by jemmyshin** [comment]
Can you provide more details about your machine? like system configuration, python version, python environment. @hsalehgh

**Comment by numb3r3** [comment]
@hsalehgh I think the latest annlite could work with M1, please try it out.
