### ISSUE TITLE
Link missing in README.md

### ISSUE THREAD

**Issue by matchyc** [jina-ai/annlite#216]
Details:
In **Document** section. Links `Github`  and `ReadTheDocs` are missing.
Please add correct and related links for community users, thanks!

**Comment by jemmyshin** [comment]
Hi, `Github` and `ReadTheDocs` are just placeholder parts so there will be no links there, we will remove them, thanks for reporting, and sorry for the confusion.

**Comment by matchyc** [comment]
> Hi, `Github` and `ReadTheDocs` are just placeholder parts so there will be no links there, we will remove them, thanks for reporting, and sorry for the confusion.

Thanks for the reply, hope more docs (except those in the docs store) can be publicly shown for dev contributors!
