### ISSUE TITLE
snapshot's index_hash has wrong value when deleting only

### ISSUE THREAD

**Issue by tommykoctur** [jina-ai/annlite#228]
Hi,

I found strange issue. 
When I call /backup after I deleted some data, snapshot name might have index_hash (date) older than loaded snapshot. 

I noticed it when I was debugging my pipeline.
It was doing this:
Loaded index (via /restore): snapshot ...snapshot-381491d61fb89706392f04870616b40c/2023-04-05#14:31:11-SNAPSHOT

Deleted data (vid /delete), then /backup ... and snapshot gets name ...snapshot-381491d61fb89706392f04870616b40c/2023-04-05#12:07:54-SNAPSHOT

and next time when I restored snapshot it gets "older" snapshot without data deletes.

Actually when I indexed some new data then call /backup it will create correct snapshot with current date 2023-04-27. 

Please note that this can only happen on a certain circumstances so I propose to redesign this function:

```python
    @property
    def index_hash(self):
        latest_commit = self.meta_table.get_latest_commit()
        date_time = latest_commit[-1] if latest_commit else None
        if date_time:
            if platform.system() == 'Windows':
                return date_time.isoformat('#', 'hours')
            return date_time.isoformat('#', 'seconds')
        else:
            import datetime

            return (
                datetime.datetime.utcnow().isoformat('#', 'hours')
                if platform.system() == 'Windows'
                else datetime.datetime.utcnow().isoformat('#', 'seconds')
```

**Comment by numb3r3** [comment]
@tommykoctur Thanks for pointing it out. It seems that the delete operation does not change the commit hash. We will fix this issue ASAP. Thank you again.
