### ISSUE TITLE
Persist Documents in a Database

### ISSUE THREAD

**Issue by myntoralex** [jina-ai/annlite#83]
Currently, only the HNSWPostgresIndexer supports persistence of Documents. Could we add the PQLiteIndexer some database persistence, not necessarily Postgres, but any database provider?

**Comment by JoanFM** [comment]
I believe the easiest way could be to support pointing to an external SQLite?

**Comment by numb3r3** [comment]
@myntoralex Currently, persistence is already supported by using **local-disk kv-store** `lmdb`. Is this local-disk persistence is what you expected? Or do you want to have **external/remote data persistence** supporting?

**Comment by numb3r3** [comment]
I see, I think you want external persistence supports actually. And there maybe two branches we can proceed:

1. supporting external database e.g., ElasticeSearch, Postgres etc.,
2. supporting object storage e.g., AWS `S3`, Google `GCS`

It would be great to get your preference, and that will help us to determine the priority of new features.

**Comment by myntoralex** [comment]
I would definitely prefer option 1, since change data capture from one database table or collection ought to be reflected in a similar data view. Thanks!

**Comment by cristianmtr** [comment]
Hey @myntoralex 

Could you elaborate on your use case? It might help clarify the direction to go
